#!/bin/sh

#
# buildtar 0.0.4
#
# (C) 2004-2006 by Jan-Benedict Glaw <jbglaw@lug-owl.de>
#
# This script is used to compile a tarball from the currently
# prepared kernel. Based upon the builddeb script from
# Wichert Akkerman <wichert@wiggy.net>.
#

set -e

#
# Some variables and settings used throughout the script
#
tmpdir="${objtree}/tar-install"
tarball="${objtree}/linux-${KERNELRELEASE}-${ARCH}.tar"


#
# Figure out how to compress, if requested at all
#
case "${1}" in
	tar-pkg)
		compress="cat"
		file_ext=""
		;;
	targz-pkg)
		compress="gzip"
		file_ext=".gz"
		;;
	tarbz2-pkg)
		compress="bzip2"
		file_ext=".bz2"
		;;
	tarxz-pkg)
		compress="xz"
		file_ext=".xz"
		;;
	*)
		echo "Unknown tarball target \"${1}\" requested, please add it to ${0}." >&2
		exit 1
		;;
esac


#
# Clean-up and re-create the temporary directory
#
rm -rf -- "${tmpdir}"
mkdir -p -- "${tmpdir}/boot"


#
# Try to install modules
#
if grep -q '^CONFIG_MODULES=y' "${objtree}/.config"; then
	make ARCH="${ARCH}" O="${objtree}" KBUILD_SRC= INSTALL_MOD_PATH="${tmpdir}" modules_install
fi


#
# Install basic kernel files
#
cp -v -- "${objtree}/System.map" "${tmpdir}/boot/System.map-${KERNELRELEASE}"
cp -v -- "${objtree}/.config" "${tmpdir}/boot/config-${KERNELRELEASE}"
cp -v -- "${objtree}/vmtronx" "${tmpdir}/boot/vmtronx-${KERNELRELEASE}"


#
# Install arch-specific kernel image(s)
#
case "${ARCH}" in
	x86|i386|x86_64)
		[ -f "${objtree}/arch/x86/boot/bzImage" ] && cp -v -- "${objtree}/arch/x86/boot/bzImage" "${tmpdir}/boot/vmtronz-${KERNELRELEASE}"
		;;
	alpha)
		[ -f "${objtree}/arch/alpha/boot/vmtronx.gz" ] && cp -v -- "${objtree}/arch/alpha/boot/vmtronx.gz" "${tmpdir}/boot/vmtronz-${KERNELRELEASE}"
		;;
	parisc*)
		[ -f "${KBUILD_IMAGE}" ] && cp -v -- "${KBUILD_IMAGE}" "${tmpdir}/boot/vmtronx-${KERNELRELEASE}"
		[ -f "${objtree}/lifimage" ] && cp -v -- "${objtree}/lifimage" "${tmpdir}/boot/lifimage-${KERNELRELEASE}"
		;;
	vax)
		[ -f "${objtree}/vmtronx.SYS" ] && cp -v -- "${objtree}/vmtronx.SYS" "${tmpdir}/boot/vmtronx-${KERNELRELEASE}.SYS"
		[ -f "${objtree}/vmtronx.dsk" ] && cp -v -- "${objtree}/vmtronx.dsk" "${tmpdir}/boot/vmtronx-${KERNELRELEASE}.dsk"
		;;
	mips)
		if [ -f "${objtree}/arch/mips/boot/compressed/vmtronx.bin" ]; then
			cp -v -- "${objtree}/arch/mips/boot/compressed/vmtronx.bin" "${tmpdir}/boot/vmtronz-${KERNELRELEASE}"
		elif [ -f "${objtree}/arch/mips/boot/compressed/vmtronx.ecoff" ]; then
			cp -v -- "${objtree}/arch/mips/boot/compressed/vmtronx.ecoff" "${tmpdir}/boot/vmtronz-${KERNELRELEASE}"
		elif [ -f "${objtree}/arch/mips/boot/compressed/vmtronx.srec" ]; then
			cp -v -- "${objtree}/arch/mips/boot/compressed/vmtronx.srec" "${tmpdir}/boot/vmtronz-${KERNELRELEASE}"
		elif [ -f "${objtree}/vmtronx.32" ]; then
			cp -v -- "${objtree}/vmtronx.32" "${tmpdir}/boot/vmtronx-${KERNELRELEASE}"
		elif [ -f "${objtree}/vmtronx.64" ]; then
			cp -v -- "${objtree}/vmtronx.64" "${tmpdir}/boot/vmtronx-${KERNELRELEASE}"
		elif [ -f "${objtree}/arch/mips/boot/vmtronx.bin" ]; then
			cp -v -- "${objtree}/arch/mips/boot/vmtronx.bin" "${tmpdir}/boot/vmtronx-${KERNELRELEASE}"
		elif [ -f "${objtree}/arch/mips/boot/vmtronx.ecoff" ]; then
			cp -v -- "${objtree}/arch/mips/boot/vmtronx.ecoff" "${tmpdir}/boot/vmtronx-${KERNELRELEASE}"
		elif [ -f "${objtree}/arch/mips/boot/vmtronx.srec" ]; then
			cp -v -- "${objtree}/arch/mips/boot/vmtronx.srec" "${tmpdir}/boot/vmtronx-${KERNELRELEASE}"
		elif [ -f "${objtree}/vmtronx" ]; then
			cp -v -- "${objtree}/vmtronx" "${tmpdir}/boot/vmtronx-${KERNELRELEASE}"
		fi
		;;
	*)
		[ -f "${KBUILD_IMAGE}" ] && cp -v -- "${KBUILD_IMAGE}" "${tmpdir}/boot/vmtronx-kbuild-${KERNELRELEASE}"
		echo "" >&2
		echo '** ** **  WARNING  ** ** **' >&2
		echo "" >&2
		echo "Your architecture did not define any architecture-dependent files" >&2
		echo "to be placed into the tarball. Please add those to ${0} ..." >&2
		echo "" >&2
		sleep 5
		;;
esac


#
# Create the tarball
#
(
	opts=
	if tar --owner=root --group=root --help >/dev/null 2>&1; then
		opts="--owner=root --group=root"
	fi
	tar cf - -C "$tmpdir" boot/ lib/ $opts | ${compress} > "${tarball}${file_ext}"
)

echo "Tarball successfully created in ${tarball}${file_ext}"

exit 0
