obj-n += crt0.o  crt0-armct.o
obj-y += crt1f.o crt1f-armct.o
obj-y += crti.o  crti-armct.o
obj-y += crtn.o  crtn-armct.o
# Dynamic link version
obj-n += crt1s.o crt1s-armct.o
obj-n += crtir.o crtir-armct.o
