EXPORT	UW	adjCurPC( W adj )
EXPORT	W	ConPort;	/* console port number */
EXPORT	UW	ConPortBps;	/* console port commnication speed (bps) */
EXPORT	void	cpuLED( W v )
EXPORT	UW	delay64us;
EXPORT	W	DipSw( void )
EXPORT	void	entMonitor( UW vec )
EXPORT	void	FlushCacheAll( void )
EXPORT	UW	getBadAddr( void )
EXPORT W	getChar( BOOL wait )
EXPORT	UW	getCurPC( void )
EXPORT	UW	getCurPSR( void )
EXPORT	UW	getRegister( W regno )
EXPORT W	getSIO( W tmo )
EXPORT W	getString( UB *str )
EXPORT ER	initSIO( W port, W speed )
EXPORT	ER	initSIO_m150( SIOCB *scb, W speed )
EXPORT	void	procCommand( FP *entp )
EXPORT	W	procExtSVC( W fno, W p1, W p2, W p3 )
EXPORT	void	procReset( void )
EXPORT	W	procSVC( W fno, W p1, W p2, W p3, W p4 )
EXPORT W	putChar( W c )
EXPORT void	putSIO( UB c )
EXPORT W	printk( const UB *str )
EXPORT	void	setBoot( UW pc )
EXPORT	W	setRegister( W regno, UW val )
EXPORT	void	setupWaitUsec( void )
EXPORT	void	sysExit(W reset)
EXPORT	void	waitMsec( UW msec )
EXPORT	void	waitNsec( UW nsec )
EXPORT	void	waitUsec( UW usec )