CONFIG_ARCH_EM1D := y
CONFIG_ARCH_MX28 := n

core-y +=  sysdepend/arm/kernel/
core-y +=  sysdepend/arm/lib/
core-$(CONFIG_ARCH_EM1D) += sysdepend/arm/mach-em1d/
core-$(CONFIG_ARCH_MX28) += sysdepend/arm/mach-mx28/
