mmcAbort(){}
mmcCmdRsp(){}
mmcDatIn(){}
mmcDatInOutStop(){}
mmcDatOut(){}
mmcMediaDetect(){}
mmcPower(){}
mmcReset(){}
mmcResume(){}
mmcRwCleanup(){}
mmcRwSetup(){}
mmcSuspend(){}
mmcTskInit(){}
mmcWriteProtect(){}
mmcXferSpeed(){}
